apiVersion: v1
kind: Secret
metadata:
  name: cluster-certs
  namespace: multi-k8s-auth
type: Opaque
# Data will be populated by setup script
# kubectl create secret generic cluster-certs --from-file=cluster-b-ca.crt=/path/to/ca.crt
