apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-auth-proxy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-auth-proxy
  template:
    metadata:
      labels:
        app: kube-auth-proxy
    spec:
      serviceAccountName: kube-auth-proxy
      containers:
      - name: kube-auth-proxy
        image: kube-auth-proxy
        args:
        - kube-auth-proxy
        {{- if .Values.tokenReviewURL }}
        - --token-review-url={{ .Values.tokenReviewURL }}
        {{- end }}
        {{- if .Values.upstream }}
        - --upstream={{ .Values.upstream }}
        {{- end }}
        - --port={{ .Values.port | default 4180 }}
        - --auth-prefix={{ .Values.authPrefix | default "/auth" }}
        ports:
        - containerPort: {{ .Values.port | default 4180 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.port | default 4180 }}
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.port | default 4180 }}
          initialDelaySeconds: 3
          periodSeconds: 10
