apiVersion: v1
kind: Service
metadata:
  name: kube-auth-proxy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: kube-auth-proxy
  ports:
  - port: 4180
    targetPort: {{ .Values.port | default 4180 }}
